name: Content Validation

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.149.0"
          extended: true

      - name: Validate Hugo build
        run: |
          echo "🔍 Validating Hugo build..."
          hugo --gc --minify --printPathWarnings
          echo "✅ Hugo build successful"

      - name: Check content structure
        run: |
          echo "📁 Checking content structure..."
          
          # Check if content directory exists
          if [ ! -d "content" ]; then
            echo "❌ Content directory not found"
            exit 1
          fi
          
          # Check if posts directory exists and has content
          if [ -d "content/posts" ]; then
            POST_COUNT=$(find content/posts -name "*.md" | wc -l)
            echo "📝 Found $POST_COUNT post(s)"
          else
            echo "ℹ️ No posts directory found"
          fi
          
          echo "✅ Content structure validation complete"

      - name: Validate frontmatter
        run: |
          echo "🏷️ Validating frontmatter..."
          
          # Only check if posts exist
          if [ -d "content/posts" ] && [ "$(find content/posts -name "*.md" | wc -l)" -gt 0 ]; then
            echo "Checking posts for required frontmatter..."
            
            # Check for titles
            MISSING_TITLES=$(find content/posts -name "*.md" -exec grep -L "^title:" {} \;)
            if [ -n "$MISSING_TITLES" ]; then
              echo "❌ Missing titles in:"
              echo "$MISSING_TITLES"
              exit 1
            fi
            
            # Check for dates  
            MISSING_DATES=$(find content/posts -name "*.md" -exec grep -L "^date:" {} \;)
            if [ -n "$MISSING_DATES" ]; then
              echo "❌ Missing dates in:"
              echo "$MISSING_DATES"
              exit 1
            fi
            
            echo "✅ All posts have required frontmatter"
          else
            echo "ℹ️ No posts found to validate"
          fi

      - name: Check Hugo configuration
        run: |
          echo "⚙️ Validating Hugo configuration..."
          
          if [ -f "hugo.yaml" ]; then
            echo "✅ Found hugo.yaml"
          elif [ -f "hugo.yml" ]; then
            echo "✅ Found hugo.yml"
          elif [ -f "config.yaml" ]; then
            echo "✅ Found config.yaml"
          elif [ -f "config.yml" ]; then
            echo "✅ Found config.yml"
          else
            echo "❌ No Hugo configuration file found"
            exit 1
          fi
          
          echo "✅ Configuration validation complete"